import 'package:uuid/uuid.dart';

import 'database_service.dart';
import '../models/transaccion.dart';
import '../models/cuenta.dart';
import '../models/categoria.dart';
import '../models/gasto_fijo.dart';
import '../models/contacto.dart';

class SampleDataService {
  final DatabaseService _databaseService = DatabaseService();
  final Uuid _uuid = const Uuid();

  Future<void> insertSampleData() async {
    try {
      // For demonstration, let's assume a user with ID 1 exists.
      // In a real app, this would be tied to the authenticated user.
      const int sampleUserId = 1;

      print('Sample data service disabled for Supabase');
    } catch (e) {
      print('Error insertando datos de ejemplo: $e');
    }
  }

  // Create default accounts for a new user
  Future<void> createDefaultAccountsForUser(int userId) async {
    try {
      final List<Cuenta> defaultAccounts = [
        Cuenta(
          idCuenta: 0, // Will be auto-generated by database
          userId: userId
              .toString(), // Convert int to String for Firebase UID compatibility
          nombre: 'Santander',
          tipo: TipoCuenta.bancaria,
          numeroCuenta: '123456789',
          bancoEntidad: 'Banco Santander',
          moneda: 'ARS',
          colorHex: '#2196F3',
          icono: 'credit_card',
          fechaCreacion: DateTime.now(),
          activa: true,
          esPrincipal: true,
        ),
        Cuenta(
          idCuenta: 0, // Will be auto-generated by database
          userId: userId
              .toString(), // Convert int to String for Firebase UID compatibility
          nombre: 'BBVA',
          tipo: TipoCuenta.bancaria,
          numeroCuenta: '987654321',
          bancoEntidad: 'Banco BBVA',
          moneda: 'ARS',
          colorHex: '#9C27B0',
          icono: 'account_balance',
          fechaCreacion: DateTime.now(),
          activa: true,
          esPrincipal: false,
        ),
        Cuenta(
          idCuenta: 0, // Will be auto-generated by database
          userId: userId
              .toString(), // Convert int to String for Firebase UID compatibility
          nombre: 'Efectivo',
          tipo: TipoCuenta.efectivo,
          moneda: 'ARS',
          colorHex: '#4CAF50',
          icono: 'money',
          fechaCreacion: DateTime.now(),
          activa: true,
          esPrincipal: false,
        ),
        Cuenta(
          idCuenta: 0, // Will be auto-generated by database
          userId: userId
              .toString(), // Convert int to String for Firebase UID compatibility
          nombre: 'Mercado Pago',
          tipo: TipoCuenta.digital,
          numeroCuenta: 'MP123456',
          bancoEntidad: 'Mercado Libre',
          moneda: 'ARS',
          colorHex: '#E91E63',
          icono: 'account_balance_wallet',
          fechaCreacion: DateTime.now(),
          activa: true,
          esPrincipal: false,
        ),
      ];

      for (var account in defaultAccounts) {
        await _databaseService.insertCuenta(account);
      }

      print('Cuentas por defecto creadas para usuario $userId');
    } catch (e) {
      print('Error creando cuentas por defecto: $e');
      rethrow;
    }
  }

  // Create default categories for a new user
  Future<void> createDefaultCategoriesForUser(int userId) async {
    try {
      final defaultCategories = [
        // Income categories
        Categoria(
          idCategoria: 0, // Will be auto-generated by database
          userId: userId
              .toString(), // Convert int to String for Firebase UID compatibility
          nombre: 'Sueldo',
          tipo: TipoCategoria.ingreso,
          colorHex: '#4CAF50',
          icono: 'work',
          descripcion: 'Ingresos por trabajo',
          fechaCreacion: DateTime.now(),
          activa: true,
        ),
        Categoria(
          idCategoria: 0, // Will be auto-generated by database
          userId: userId
              .toString(), // Convert int to String for Firebase UID compatibility
          nombre: 'Ventas',
          tipo: TipoCategoria.ingreso,
          colorHex: '#8BC34A',
          icono: 'shopping_cart',
          descripcion: 'Ingresos por ventas',
          fechaCreacion: DateTime.now(),
          activa: true,
        ),
        Categoria(
          idCategoria: 0, // Will be auto-generated by database
          userId: userId
              .toString(), // Convert int to String for Firebase UID compatibility
          nombre: 'Otros Ingresos',
          tipo: TipoCategoria.ingreso,
          colorHex: '#CDDC39',
          icono: 'attach_money',
          descripcion: 'Otros tipos de ingresos',
          fechaCreacion: DateTime.now(),
          activa: true,
        ),
        // Expense categories
        Categoria(
          idCategoria: 0, // Will be auto-generated by database
          userId: userId
              .toString(), // Convert int to String for Firebase UID compatibility
          nombre: 'Alimentación',
          tipo: TipoCategoria.gasto,
          colorHex: '#FF9800',
          icono: 'restaurant',
          descripcion: 'Comida y bebidas',
          fechaCreacion: DateTime.now(),
          activa: true,
        ),
        Categoria(
          idCategoria: 0, // Will be auto-generated by database
          userId: userId
              .toString(), // Convert int to String for Firebase UID compatibility
          nombre: 'Transporte',
          tipo: TipoCategoria.gasto,
          colorHex: '#2196F3',
          icono: 'directions_car',
          descripcion: 'Gasolina, transporte público, etc.',
          fechaCreacion: DateTime.now(),
          activa: true,
        ),
        Categoria(
          idCategoria: 0, // Will be auto-generated by database
          userId: userId
              .toString(), // Convert int to String for Firebase UID compatibility
          nombre: 'Servicios',
          tipo: TipoCategoria.gasto,
          colorHex: '#9C27B0',
          icono: 'bolt',
          descripcion: 'Luz, gas, internet, teléfono',
          fechaCreacion: DateTime.now(),
          activa: true,
        ),
        Categoria(
          idCategoria: 0, // Will be auto-generated by database
          userId: userId
              .toString(), // Convert int to String for Firebase UID compatibility
          nombre: 'Salud',
          tipo: TipoCategoria.gasto,
          colorHex: '#F44336',
          icono: 'local_hospital',
          descripcion: 'Medicinas, consultas médicas',
          fechaCreacion: DateTime.now(),
          activa: true,
        ),
        Categoria(
          idCategoria: 0, // Will be auto-generated by database
          userId: userId
              .toString(), // Convert int to String for Firebase UID compatibility
          nombre: 'Educación',
          tipo: TipoCategoria.gasto,
          colorHex: '#3F51B5',
          icono: 'school',
          descripcion: 'Cursos, libros, material educativo',
          fechaCreacion: DateTime.now(),
          activa: true,
        ),
        Categoria(
          idCategoria: 0, // Will be auto-generated by database
          userId: userId
              .toString(), // Convert int to String for Firebase UID compatibility
          nombre: 'Entretenimiento',
          tipo: TipoCategoria.gasto,
          colorHex: '#E91E63',
          icono: 'movie',
          descripcion: 'Cine, streaming, salidas',
          fechaCreacion: DateTime.now(),
          activa: true,
        ),
        Categoria(
          idCategoria: 0, // Will be auto-generated by database
          userId: userId
              .toString(), // Convert int to String for Firebase UID compatibility
          nombre: 'Compras',
          tipo: TipoCategoria.gasto,
          colorHex: '#795548',
          icono: 'shopping_bag',
          descripcion: 'Ropa, electrónicos, hogar',
          fechaCreacion: DateTime.now(),
          activa: true,
        ),
      ];

      for (var category in defaultCategories) {
        await _databaseService.insertCategoria(category);
      }

      print('Categorías por defecto creadas para usuario $userId');
    } catch (e) {
      print('Error creando categorías por defecto: $e');
      rethrow;
    }
  }

  Future<void> _insertSampleFixedExpenses(int userId) async {
    // Sample data generation disabled for Supabase
    return;
  }

  Future<void> _insertSampleTransactions(int userId) async {
    // Sample data generation disabled for Supabase
    return;
  }

  Future<void> _insertSampleContacts(int userId) async {
    // Sample data generation disabled for Supabase
    return;
  }

  // Legacy methods removed for Supabase migration
}
