// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase project.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwob8g-4Cuzo3F3Ih-9YBYPq-WS_S6Acs',
    appId: '1:439049372849:web:your-web-app-id', // Need to fill this
    messagingSenderId: '439049372849',
    projectId: 'daybyday-5ef1a',
    authDomain: 'daybyday-5ef1a.firebaseapp.com',
    storageBucket: 'daybyday-5ef1a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwob8g-4Cuzo3F3Ih-9YBYPq-WS_S6Acs',
    appId: '1:439049372849:android:d9ef2ca1a6b28e30de8e90',
    messagingSenderId: '439049372849',
    projectId: 'daybyday-5ef1a',
    storageBucket: 'daybyday-5ef1a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwob8g-4Cuzo3F3Ih-9YBYPq-WS_S6Acs',
    appId: '1:439049372849:ios:your-ios-app-id', // Need to fill this
    messagingSenderId: '439049372849',
    projectId: 'daybyday-5ef1a',
    storageBucket: 'daybyday-5ef1a.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwob8g-4Cuzo3F3Ih-9YBYPq-WS_S6Acs',
    appId: '1:439049372849:web:your-web-app-id', // Need to fill this
    messagingSenderId: '439049372849',
    projectId: 'daybyday-5ef1a',
    authDomain: 'daybyday-5ef1a.firebaseapp.com',
    storageBucket: 'daybyday-5ef1a.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwob8g-4Cuzo3F3Ih-9YBYPq-WS_S6Acs',
    appId: '1:439049372849:web:your-web-app-id', // Need to fill this
    messagingSenderId: '439049372849',
    projectId: 'daybyday-5ef1a',
    authDomain: 'daybyday-5ef1a.firebaseapp.com',
    storageBucket: 'daybyday-5ef1a.firebasestorage.app',
  );
}
